### ISSUE TITLE
Component refs stored in other components

### ISSUE THREAD

**Issue by sschmid** [ShadeSlider/Entitas-RTS-Template#1]
Hi,

I came here from this issue on Entitas
https://github.com/sschmid/Entitas-CSharp/issues/559

I saw you're using references to components in 
[DragSelectionDataComponent](https://github.com/ShadeSlider/Entitas-RTS-Template/blob/master/Assets/Sources/Components/Input/DragSelectionDataComponent.cs)

You should rather store the component values instead the refs. Components are object pooled and reused and this can lead to nasty bugs. In general, I recommend not having pointers to entities or components.

**Comment by ShadeSlider** [comment]
@sschmid Hi, Simon!
Thanks for letting me know! That's why I wanted community feedback for my template in the first place :)
DragSelection system was one of the first things I've done after starting with Entitas, so it is less than ideal.
I'll make sure to upload a fix as soon as I can.

**Comment by ShadeSlider** [comment]
@sschmid [Refactored](https://github.com/ShadeSlider/Entitas-RTS-Template/commit/36922d6e047c895da43b31cb2eb4c3e9b54c740e#diff-3812a57268ac1d93de2ff45cd768a4d0) the example to eliminate references components within components. 
If it looks good, I will close the issue :)
